GET http://localhost:3001/

###

GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/9

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Chinwe Chukwuogor",
    "number": "0234-24445-21"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Mark Houston",
    "number": "34-24445-21"
}

###

POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "Mark Nwankwo",
    "number": "134-24445-21"
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "May Alfred",
    "number": "132-2085-2186"
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "Mark Nwankwo",
    "number": "134-24445-21"
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "Mark Nwankwo",
    "number": "134-24445-21"
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "M",
    "number": "134-24445-21"
}

###
PUT http://localhost:3001/api/persons/6576f0b6d3c2049abf207657
content-type: application/json

{
    "name" : "Mark Nwankwo",
    "number": "145-21"
}

###
PUT http://localhost:3001/api/persons/6576ee12d3c2049abf20764e
content-type: application/json

{
    "name" : "Chinelomu Ikedindu",
    "number": "45-210-994"
}